### ISSUE TITLE
Ошибка the data couldn’t be read

### ISSUE THREAD

**Issue by IAMTHEBURT** [illabo/IIDadata#1]
Добрый день
При вводе адресов (например если ввести 'Москва') в консоли появляется ошибка

Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "suggestions", intValue: nil), _JSONKey(stringValue: "Index 1", intValue: 1), CodingKeys(stringValue: "data", intValue: nil), CodingKeys(stringValue: "metro", intValue: nil)], debugDescription: "Expected to decode Dictionary<String, Any> but found an array instead.", underlyingError: nil))

The data couldn’t be read because it isn’t in the correct format.

Запускаю из Example. Так происходит не всегда, некоторые запросы работают правильно.

Спасибо

**Comment by illabo** [comment]
Кажется пофиксал. Замените в `Podfile`'е строку добавления либы на такую.
```ruby
pod 'IIDadata', :git => https://github.com/illabo/IIDadata.git', :branch => 'hotfix'
```
И затем сделайте `pod install`.
Проверьте, пожалуйста. Скорее всего все ок. Я не могу протестить этот кейс, так как у меня не «максимальный» тариф и я всегда nil в качестве метро получаю.
Если все в порядке сделаю релиз с фиксом.

**Comment by IAMTHEBURT** [comment]
Спасибо за ответ
Ошибка осталась, но немного поменялась

typeMismatch(Swift.String, Swift.DecodingError.Context(codingPath: [CodingKeys(stringValue: "suggestions", intValue: nil), _JSONKey(stringValue: "Index 1", intValue: 1), CodingKeys(stringValue: "data", intValue: nil), CodingKeys(stringValue: "metro", intValue: nil), _JSONKey(stringValue: "Index 0", intValue: 0), CodingKeys(stringValue: "distance", intValue: nil)], debugDescription: "Expected to decode String but found a number instead.", underlyingError: nil))
The data couldn’t be read because it isn’t in the correct format.

**Comment by illabo** [comment]
@superbaby70, проверьте, пожалуйста, еще раз. Не забудьте запустить `pod install`.

**Comment by illabo** [comment]
@superbaby70, добавил изменения на релизный бранч.
```ruby
pod 'IIDadata', '~> 0.2.4'
```

**Comment by IAMTHEBURT** [comment]
Все заработало
Спасибо большое
